### Machine Learning Tools 
#### Introduction to XGBoost
+ eXtreme Gradient Boosting

+ pip install xgboost


#### What is Boosting and Gradient Boosting?
+ Boosting : an ensemble technique of adding new models to correct the errors made by existing models
+ Boosting: is an ensemble method that seeks to create a strong classifier (model) based on “weak” classifiers. 
+ By adding models on top of each other iteratively, the errors of the previous model are corrected by the next predictor, until the training data is accurately predicted or reproduced by the model.
+ Gradient Boosting:
+ an ensemble method that sequentially adds predictors and corrects previous models. 
+ Procedure: instead of assigning different weights to the classifiers after every iteration, this method fits the new model to new residuals of the previous prediction and then minimizes the loss when adding the latest prediction
+ Gradient ?: use of gradient descent algorithm to minimise the loses during new models creation

#### Tips
+ Has a DMatrix( for performance and efficiency)
+ Works with only numerical values
+ For Categorical you need to one-hot-encode it/label encode it

#### Reasons For using XGBoost
+ Execution Speed
+ Model Performance.

Input variables:
   #### bank client data:
   1 - age (numeric)
   2 - job : type of job (categorical: "admin.","blue-collar","entrepreneur","housemaid","management","retired","self-employed","services","student","technician","unemployed","unknown")
   3 - marital : marital status (categorical: "divorced","married","single","unknown"; note: "divorced" means divorced or widowed)
   4 - education (categorical: "basic.4y","basic.6y","basic.9y","high.school","illiterate","professional.course","university.degree","unknown")
   5 - default: has credit in default? (categorical: "no","yes","unknown")
   6 - housing: has housing loan? (categorical: "no","yes","unknown")
   7 - loan: has personal loan? (categorical: "no","yes","unknown")
   #### related with the last contact of the current campaign:
   8 - contact: contact communication type (categorical: "cellular","telephone") 
   9 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")
  10 - day_of_week: last contact day of the week (categorical: "mon","tue","wed","thu","fri")
  11 - duration: last contact duration, in seconds (numeric). Important note:  this attribute highly affects the output target (e.g., if duration=0 then y="no"). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
   ##### other attributes:
  12 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)
  13 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
  14 - previous: number of contacts performed before this campaign and for this client (numeric)
  15 - poutcome: outcome of the previous marketing campaign (categorical: "failure","nonexistent","success")
   ##### social and economic context attributes
  16 - emp.var.rate: employment variation rate - quarterly indicator (numeric)
  17 - cons.price.idx: consumer price index - monthly indicator (numeric)     
  18 - cons.conf.idx: consumer confidence index - monthly indicator (numeric)     
  19 - euribor3m: euribor 3 month rate - daily indicator (numeric)
  20 - nr.employed: number of employees - quarterly indicator (numeric)

  Output variable (desired target):
  21 - y - has the client subscribed a term deposit? (binary: "yes","no")
  ["age","job","marital","education","default","housing","loan","contact","month","day_of_week","duration","campaign","pdays","previous","poutcome","emp.var.rate","cons.price.idx","cons.conf.idx","euribor3m","nr.employed","label"]

In [ ]:
# Load Pkgs
import pandas as pd
import numpy as np
import xgboost as xgb

In [ ]:
# Load Dataset (California Housing)
df = pd.read_csv("bank-additional-full.csv",sep=";")

In [ ]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
# Shape
df.shape

(41188, 21)

In [ ]:
# Columns
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [ ]:
# Check Missing Values
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [ ]:
df.dtypes

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

### Encode our categorical data
+ Get Dummies

In [ ]:
# Get All Columns that are object
df.columns[df.dtypes == 'object']

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome', 'y'],
      dtype='object')

In [ ]:
#Using Get Dummies
pd.get_dummies(df,df.columns[df.dtypes == 'object'])

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,y_no,y_yes
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
5,45,198,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
6,59,139,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
7,41,217,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
8,24,380,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
9,25,50,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
10,41,55,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
11,25,222,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
12,29,137,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
13,57,293,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
14,35,146,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
15,54,174,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
16,35,312,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
17,46,440,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
18,50,353,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
19,39,195,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
20,30,38,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
21,55,262,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
22,55,342,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
23,41,181,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
24,37,172,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
25,35,99,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
26,59,93,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
27,39,233,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
28,54,255,2,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
29,55,362,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,1,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41158,35,363,1,999,0,-1.1,94.767,-50.8,1.035,4963.6,...,0,0,0,1,0,0,1,0,0,1
41159,35,514,1,9,4,-1.1,94.767,-50.8,1.035,4963.6,...,0,0,0,1,0,0,0,1,0,1
41160,33,843,1,999,0,-1.1,94.767,-50.8,1.035,4963.6,...,0,0,0,1,0,0,1,0,0,1
41161,33,510,1,999,1,-1.1,94.767,-50.8,1.035,4963.6,...,0,0,0,1,0,1,0,0,1,0
41162,60,347,2,4,1,-1.1,94.767,-50.8,1.035,4963.6,...,0,0,0,1,0,0,0,1,1,0
41163,35,385,3,4,2,-1.1,94.767,-50.8,1.035,4963.6,...,0,0,0,1,0,0,0,1,0,1
41164,54,1868,2,10,1,-1.1,94.767,-50.8,1.035,4963.6,...,0,0,0,1,0,0,0,1,0,1
41165,38,403,2,999,0,-1.1,94.767,-50.8,1.030,4963.6,...,0,0,0,0,1,0,1,0,0,1
41166,32,651,1,999,1,-1.1,94.767,-50.8,1.030,4963.6,...,0,0,0,0,1,1,0,0,0,1
41167,32,236,3,999,0,-1.1,94.767,-50.8,1.030,4963.6,...,0,0,0,0,1,0,1,0,1,0
41168,38,144,2,999,0,-1.1,94.767,-50.8,1.030,4963.6,...,0,0,0,0,1,0,1,0,1,0
41169,62,154,5,999,0,-1.1,94.767,-50.8,1.030,4963.6,...,0,0,0,0,1,0,1,0,1,0
41170,40,293,2,999,4,-1.1,94.767,-50.8,1.030,4963.6,...,0,0,0,0,1,1,0,0,1,0
41171,33,112,1,999,0,-1.1,94.767,-50.8,1.031,4963.6,...,0,0,1,0,0,0,1,0,0,1
41172,31,353,1,999,0,-1.1,94.767,-50.8,1.031,4963.6,...,0,0,1,0,0,0,1,0,0,1
41173,62,329,1,999,2,-1.1,94.767,-50.8,1.031,4963.6,...,0,0,1,0,0,1,0,0,0,1
41174,62,208,1,1,6,-1.1,94.767,-50.8,1.031,4963.6,...,0,0,1,0,0,0,0,1,0,1
41175,34,180,1,999,2,-1.1,94.767,-50.8,1.031,4963.6,...,0,0,1,0,0,1,0,0,1,0
41176,38,360,1,999,0,-1.1,94.767,-50.8,1.031,4963.6,...,0,0,1,0,0,0,1,0,1,0
41177,57,124,6,999,0,-1.1,94.767,-50.8,1.031,4963.6,...,0,0,1,0,0,0,1,0,1,0
41178,62,483,2,6,3,-1.1,94.767,-50.8,1.031,4963.6,...,0,0,1,0,0,0,0,1,0,1
41179,64,151,3,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,1,0,1,0
41180,36,254,2,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,1,0,1,0
41181,37,281,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,1,0,0,1
41182,29,112,1,9,1,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,0,1,1,0
41183,73,334,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,1,0,0,1
41184,46,383,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,1,0,1,0
41185,56,189,2,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,1,0,1,0
41186,44,442,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,1,0,0,1
41187,74,239,3,999,1,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,1,0,0,1,0

In [ ]:
df.dtypes

age                 int64
job                  int8
marital              int8
education            int8
default              int8
housing              int8
loan                 int8
contact              int8
month                int8
day_of_week          int8
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome             int8
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                    int8
dtype: object

In [ ]:
# Split dataset
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#### Building Models

In [ ]:
### Using Decision Tree Classifier

In [ ]:
# Load Pkg
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dTree_clf = DecisionTreeClassifier()

In [ ]:
dTree_clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [ ]:
# Prediction
y_pred2 = dTree_clf.predict(X_test)

In [ ]:
y_pred2

array([1, 0, 0, ..., 1, 0, 0], dtype=int8)

In [ ]:
print("Accuracy of Model::",accuracy_score(y_test,y_pred2))

Accuracy of Model:: 0.8929351784413693

### Using XGBoost

In [ ]:
xgb_classifier = xgb.XGBClassifier()

In [ ]:
xgb_classifier.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [ ]:
predictions = xgb_classifier.predict(X_test)

In [ ]:
predictions

array([0, 0, 0, ..., 1, 0, 0], dtype=int8)

In [ ]:
print("Accuracy of Model::",accuracy_score(y_test,predictions))

Accuracy of Model:: 0.9225540179655256